### ISSUE TITLE
Support for whitelisting ips/ports that can be forwarded to

### ISSUE THREAD

**Issue by sheerun** [ginuerzh/gosocks5#1]
I'd like to allow SOCKS5 server to forward only to specific set of ips/ports as a security measure. This would be the equivalent of `client pass` parameter from socksd: https://www.youtube.com/watch?v=Hb28SqX5cWg

I imagine this could be used in gost, like so:

server
```
gost -L socks://localhost:8000?whitelist=127.0.0.1:9000
```

client
```
gost -L :3000/127.0.0.1:9000 -F socks://1.2.3.4:8000
```

The command above would expose some admin dashboard on port 9000 on remote host on port 3000 on local machine. Whitelisting would make it impossible to perform following:

```
gost -L :3000/127.0.0.1:8000 -F socks://1.2.3.4:8000
``` 

where there's admin panel on port 8000 on remote host that client shouldn't get access to (as well as other virtual network addresses server has access to, but client shoudn't).

**Comment by ginuerzh** [comment]
It is a good idea from a security point of view, I have created an [issue](https://github.com/ginuerzh/gost/issues/87) in gost.
